services:
  caddy:
    image: caddy:2.11.3
    build:
      dockerfile: Dockerfile.caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  caddy_data:
  caddy_config:
