FROM caddy:2-builder AS builder
RUN xcaddy build --with github.com/greenpau/caddy-security

# Stage 2: Create final lightweight production image
FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy