x-common:
  &default-restart
  restart: always

x-extra-hosts:
  &host-gateway
  extra_hosts:
    - host.docker.internal:host-gateway

services:
  jupyter:
    <<: [*default-restart, *host-gateway]
    build:
      dockerfile: Dockerfile.jupyter
    volumes:
      - jupyter-data:/home
      - /mnt:/mnt
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    ports:
      - 3002:8000
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_OAUTH_CALLBACK_URL: ${JUPYTER_OAUTH_CALLBACK_URL}
      ADMIN_USERS: ${ADMIN_USERS}
      ALLOWED_USERS: ${ALLOWED_USERS}

  openwebui:
    <<: [*default-restart, *host-gateway]
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-slim}
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_DRIVE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_DRIVE_API_KEY: ${GOOGLE_DRIVE_API_KEY}
      OPENID_PROVIDER_URL: ${OPENID_PROVIDER_URL}
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OPENAI_API_BASE_URL: http://litellm:4000/v1
    pull_policy: always

  ollama:
    <<: [*default-restart]
    image: cagataygurturk/docker-ssh-tunnel:latest
    volumes:
      # Mount your local private SSH key (read-only)
      - ~/.ssh:/root/ssh:ro
    environment:
      LOCAL_PORT: 11434
      REMOTE_HOST: localhost
      REMOTE_PORT: 11434
      TUNNEL_HOST: ${OLLAMA_HOST}
    ports:
      - 11434:11434
    pull_policy: always

  hermes:
    <<: [*default-restart, *host-gateway]
    build:
      context: .
      dockerfile: Dockerfile.hermes
      pull: true
    volumes:
      - hermes-data:/opt/data
    ports:
      - 8642:8642
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      API_SERVER_ENABLED: true
      API_SERVER_KEY: your-secure-key-fob!
      API_SERVER_HOST: 0.0.0.0
      SEARXNG_URL: http://searxng-core:8080
    command: ["gateway"]

  openclaw:
    <<: [*default-restart, *host-gateway]
    build:
      context: .
      dockerfile: Dockerfile.openclaw
      pull: true
      secrets:
        - clawhub_api_key
      args:
        - OPENCLAW_TAG=${OPENCLAW_TAG-slim}
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GOOGLE_MAPS_LANG: ${GOOGLE_MAPS_LANG}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
      BAIDU_API_KEY: ${BAIDU_API_KEY}
      CLAWHUB_API_KEY: ${CLAWHUB_API_KEY}
      ZHIPU_API_KEY: ${ZHIPU_API_KEY}
      OPENCLAW_NO_RESPAWN: 1
      NODE_COMPILE_CACHE: /var/tmp/openclaw-compile-cache
      SEARXNG_BASE_URL: http://searxng-core:8080
    volumes:
      - openclaw-data:/home/node
    ports:
      - 18789:18789

  searxng-core:
    <<: [*default-restart]
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    env_file: ./.env
    volumes:
      - ./searxng-settings.yml/:/etc/searxng/settings.yml:ro
      - core-data:/var/cache/searxng/

  searxng-valkey:
    <<: [*default-restart]
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data:/data/

  litellm:
    <<: [*default-restart]
    build:
      dockerfile: Dockerfile.litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yml:/app/config.yml
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      POE_API_KEY: ${POE_API_KEY}
    command: [ "--config", "/app/config.yml", "--port", "4000" ]


volumes:
  open-webui:
  hermes-data:
  core-data:
  valkey-data:
  openclaw-data:
  jupyter-data:

secrets:
  clawhub_api_key:
    environment: "CLAWHUB_API_KEY"

