ARG HERMES_TAG=latest
FROM nousresearch/hermes-agent:${HERMES_TAG}
COPY --chmod=775 hermes-config.sh hermes-config.sh
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl python3-pip && \
   ./hermes-config.sh && \
   apt-get clean && \
   rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /usr/lib/python3.*/EXTERNALLY-MANAGED /root/.cache 
