services:

  redmine:
    image: redmine_local
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - redmine-files:/usr/share/redmine/files
      - redmine-themes:/usr/src/redmine/public/themes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=Host(`project.${DOMAIN-localhost}`)"
      - "traefik.http.routers.project.entrypoints=websecure"
      - "traefik.http.routers.project.tls=true"
      - "traefik.http.routers.project.tls.certresolver=myresolver"
      - "traefix.http.services.project.loadbalancer.server.port=3000"
      - "traefix.docker.network=proxy-network"
    networks:
      - default
      - proxy-network

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: redmine
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

volumes:
   redmine-files:
   redmine-themes:
   postgres_data:

networks:
   proxy-network:
     name: proxy-network
