services:
  jupyter:
    build: .
    volumes:
      - ./jupyterhub_config.py:/app/jupyterhub_config.py
      - jupyter-data:/home
      - /mnt:/mnt
    ports:
      - 3002:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_OAUTH_CALLBACK_URL: ${GOOGLE_OAUTH_CALLBACK_URL}
      ADMIN_USERS: ${ADMIN_USERS}
      ALLOWED_USERS: ${ALLOWED_USERS}
  ollama:
    image: cagataygurturk/docker-ssh-tunnel:latest
    volumes:
      # Mount your local private SSH key (read-only)
      - ~/.ssh/id_ed25519:/root/ssh/id_ed25519:ro
    environment:
      LOCAL_PORT: 11434
      REMOTE_HOST: localhost
      REMOTE_PORT: 11434
      TUNNEL_HOST: ${OLLAMA_HOST}

volumes:
  jupyter-data:
